baseURL: "http://sassfactoryimprov.com"
languageCode: "en-us"
title: "Sass Factory"

menu:
  main:
    - identifier: "shows"
      name: "Shows"
      url: "/shows/"
      weight: 1
    - identifier: "cast"
      name: "Current Cast"
      url: "/cast/"
      weight: 2
    - identifier: "gallery"
      name: "Gallery"
      url: "/gallery/"
      weight: 3
    - identifier: "emeritus"
      name: "Sassies Emeritus"
      url: "/emeritus/"
      weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  teamPhoto: "/images/team-photo.jpg"
  imagekit:
    endpoint: "https://ik.imagekit.io/sassfactory"
    path: "/gallery"