baseURL: "http://localhost:1313"
languageCode: "en-us"
title: "Sass Factory"

menu:
  main:
    - identifier: "shows"
      name: "Shows"
      url: "/shows/"
      weight: 1
    - identifier: "cast"
      name: "Current Cast"
      url: "/cast/"
      weight: 2
    - identifier: "emeritus"
      name: "Sassies Emeritus"
      url: "/emeritus/"
      weight: 3

markup:
  goldmark:
    renderer:
      unsafe: true